# Generated by Django 5.2.1 on 2025-05-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Inativo'), (1, 'Ativo')], default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.funcao')),
            ],
        ),
    ]
