# Generated by Django 5.2.1 on 2025-06-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcao',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='funcao',
            new_name='role',
        ),
    ]
