# Generated by Django 5.2.1 on 2025-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Cadeira de Rodas'), (1, 'Muletas'), (2, 'Cama Hospitalar')]),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='type',
            field=models.IntegerField(choices=[(0, 'Cadeira de Rodas'), (1, 'Muletas'), (2, 'Cama Hospitalar')]),
        ),
    ]
