# Generated by Django 5.2.1 on 2025-09-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_equipment_type_alter_historicalequipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalloans',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='requester',
        ),
    ]
